#!/bin/sh
pm uninstall -k --user 0 com.miui.analytics 
pm uninstall -k --user 0 com.facebook.system 
pm uninstall -k --user 0 com.facebook.appmanager
pm uninstall -k --user 0 com.facebook.services  
pm uninstall -k --user 0 com.xiaomi.glgm 
pm uninstall -k --user 0 com.xiaomi.mipicks 
pm uninstall -k --user 0 com.android.hotwordenrollment.xgoogle 
pm uninstall -k --user 0 com.android.hotwordenrollment.okgoogle 
pm uninstall -k --user 0 com.google.android.apps.googleassistant
pm uninstall -k --user 0 com.google.android.apps.subscriptions.red
pm uninstall -k --user 0 com.xiaomi.payment  
pm uninstall -k --user 0 com.miui.msa.global
pm uninstall -k --user 0 com.xiaomi.midrop 
pm uninstall -k --user 0 com.mi.android.globalminusscreen 
pm uninstall -k --user 0 com.crazy.juicer.xm
pm uninstall -k --user 0 com.alibaba.aliexpresshd
pm uninstall -k --user 0 com.kingsgroup.ss.xiaomi
pm uninstall -k --user 0 com.jewelsblast.ivygames.Adventure.free
pm uninstall -k --user 0 com.booking
pm uninstall -k --user 0 com.zhiliaoapp.musically
pm uninstall -k --user 0 com.sukhavati.gotoplaying.bubble.BubbleShooter.mint
pm uninstall -k --user 0 com.mi.global.pocostore
pm uninstall -k --user 0 com.amazon.appmanager
pm uninstall -k --user 0 com.block.puzzle.game.hippo.mi
pm uninstall -k --user 0 com.facebook.katana
pm uninstall -k --user 0 com.amazon.mShop.android.shopping
pm uninstall -k --user 0 com.logame.eliminateintruder3d
pm uninstall -k --user 0 com.google.android.apps.photos
pm uninstall -k --user 0 com.mi.global.pocobbs
pm uninstall -k --user 0 com.amazon.mp3
pm uninstall -k --user 0 com.google.android.apps.magazines
pm uninstall -k --user 0 com.mintgames.triplecrush.tile.fun
pm uninstall -k --user 0 ctrip.english
pm uninstall -k --user 0 com.netflix.mediaclient
